name: 4craft
version: 0.01
main: com.wanderingcorgi.minecraft.Main
commands:
   b:
      description: This is the base command
      usage: /b
      permission-message: You don't have <permission>
   f:
      description: This is the base command alternative
      usage: /b
      permission-message: You don't have <permission>